### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by RelouseOld** [thedoritos/unimgpicker#16]
Hello, I can't build it.
My Unity version is 2017.4.0
Errors:
![image](https://user-images.githubusercontent.com/13157586/37933492-0ca828e0-3154-11e8-8470-35bd8ebe94cf.png)
![image 1](https://user-images.githubusercontent.com/13157586/37933499-13da4b0c-3154-11e8-9de3-c2240e54eaf3.png)
[Error text (1).txt](https://github.com/thedoritos/unimgpicker/files/1849572/Error.text.1.txt)

What can I do for solve it?
Thank you!)

**Comment by NickvdLaan** [comment]
I've ran into this same issue as well.
I fixed it by changing the **project settings** for android. Change the scripting backend to **il2cpp** and also add the **Android NDK**. Finally change your build system from **Gradle to Interna**l. Not sure why it doesn't work on gradle though..

**Comment by RelouseOld** [comment]
Thank you!
How can it harm for my project? Or it couldn't harm? (I'm talking about il2cpp and internal build system)

**Comment by NickvdLaan** [comment]
IL2CPP is a Unity-developed scripting back-end which you can use as an alternative to Mono when building projects for some platforms. See more here [https://docs.unity3d.com/Manual/IL2CPP.html](https://docs.unity3d.com/Manual/IL2CPP.html)

Depending on your project Im not sure if it would harm it. Also the internal build system vs gradle see [https://stackoverflow.com/questions/46798774/unity-build-systems-internal-vs-gradle](url)

**Comment by mole84** [comment]
Someone find a solution for gradle???

**Comment by thedoritos** [comment]
Hi! This was because unimgpicker.jar was containing BuildConfig.class. Since Unimgpicker doesn't have to use BuildConfig, I removed it from jar on v1.1.2. It should pass build.

https://github.com/thedoritos/unimgpicker/releases/tag/v1.1.2
