### ISSUE TITLE
Error building for Android

### ISSUE THREAD

**Issue by snowman745** [thedoritos/unimgpicker#18]
When trying to build for Android, we get these blocking errors (We are using Unity 2017):

The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.

**Comment by mole84** [comment]
- same problem for me with Unity 2017 and Gradle 4.1

I´ve build it without "Gradle" and set it to "internal" before build and than it works. Maybe this helps you...
But it would be fine if thedoritos could fix it.

**Comment by virgilcwylie** [comment]
Indeed it does fix the Multiple Dex file define error as well.
