### ISSUE TITLE
Saving Image

### ISSUE THREAD

**Issue by shraddha360** [thedoritos/unimgpicker#19]
How can we save the image,So that after closing and reopening the app Image should be available?

**Comment by kirax999** [comment]
the plugin copies the image in the application you just have to save the location and the name of the image then after and at the start () of set the image in your block

**Comment by shraddha360** [comment]
Worked Well , Thank you

**Comment by yohaan21** [comment]
or you can convert it into a string and save it as playerpref . and when you require you can access from playerpref 

image to string
```
Texture2D tex = (Texture2D)texture;
byte[] imagebyte = tex.EncodeToPNG();
string profileimagestring = System.Convert.ToBase64String(imagebyte);
PlayerPrefs.SetString("image", profileimagestring);

```
String to image
```
byte[] imagebytetodp = System.Convert.FromBase64String(PlayerPrefs.GetString("image");
Texture2D imageback = new Texture2D(128, 128);
imageback.LoadImage(imagebytetodp);
imageback.Apply();

image.sprite= Sprite.Create(imageback, new Rect(0, 0, imageback.width, imageback.height), new Vector2());
```
