### ISSUE TITLE
Android Build failure

### ISSUE THREAD

**Issue by yayaigo2010** [thedoritos/unimgpicker#21]
I run build android. it will popup dialog below
Build failure
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/kakeragames/unimgpicker/BuildConfig; See the Console for details.

How to fix it?

**Comment by nitishmehta3** [comment]
@thedoritos : I am facing the same issue on Android Gradle build, is there any solution or maybe a work around for this?

**Comment by thedoritos** [comment]
Hi! This was because `unimgpicker.jar` was containing `BuildConfig.class`. Since Unimgpicker doesn't have to use BuildConfig, I removed it from jar on v1.1.2. It should pass build.

https://github.com/thedoritos/unimgpicker/releases/tag/v1.1.2
