### ISSUE TITLE
Doesn't work with WebGL 

### ISSUE THREAD

**Issue by mosquito2019** [thedoritos/unimgpicker#26]
when I export it to WebGL, the Button does not work. Is it possible to work for online games ?

**Comment by thedoritos** [comment]
Hi, @mosquito2019 

Thanks for trying. However I don't think this library would work on WebGL. I built this library is for iOS & Android.

Thank you.

**Comment by thedoritos** [comment]
WebGL is out of the scope of this project. I close this issue. Thanks for trying :)
