### ISSUE TITLE
Build with the latest Unity

### ISSUE THREAD

**Issue by thedoritos** [thedoritos/unimgpicker#27]
#25, #21, #18, #16

**Comment by ming436534** [comment]
I fixed the problem after spending some time... (not short).
You guys can come to my fork to see how I fix it [https://github.com/ming436534/unimgpicker](https://github.com/ming436534/unimgpicker)

## Differences between the original project
- Update to support Unity 2018
- Fixed the MultiDex error by including the `classes.jar` with `provided`
- Update dependencies in the `unimgpicker/build.gradle` file
- Only include the `XcodeConfigurator.cs` file when the platform is iOS
- Changed the file structure in Assets/Plugins/Android

**Comment by rafadante** [comment]
Thanks ming436534, it is working fine with Unity 2018.3.2.f1
