### ISSUE TITLE
How to check image orientation of image

### ISSUE THREAD

**Issue by yohaan21** [thedoritos/unimgpicker#33]
Hi first of all thanks a ton for this awesome plugin .  
I was wondering if i can somehow check the orientation of the image, as few images which i pick are 90 degrees right rotated. 

![image rotate issue](https://user-images.githubusercontent.com/52163527/60020530-d47d4980-96ad-11e9-98c0-69ac40e92c5f.PNG)

**Comment by ImThaDude** [comment]
#7 
See if this solves your problem.

**Comment by devalmistry** [comment]
It's Showing Errors when I try to add this solution with jar file. Why this orientation is not included with main Github package. Please help.

**Comment by thedoritos** [comment]
Unimgpicker now has new implementation which simply returns a copy of the selected image file.
It allows you to read metadata from the file such as EXIF.

**Comment by thedoritos** [comment]
See #9
