### ISSUE TITLE
No apps can perform this action

### ISSUE THREAD

**Issue by koljanich** [thedoritos/unimgpicker#4]
Hello! Great unity addon! On devices with Android 4.2.1 all works fine. But old china device E1901_v77 (Android 4.1.1, 2 Core, 512RAM) when I press Show Picker I see only window: "No apps can perform this action". On Doogee (LEO_DG280) with android 5.0 window Gallerey show, but when I select image error window: "Unfortunatley, unimgpicker has stopped" and Gallerey shows again.

**Comment by thedoritos** [comment]
Hi, @koljanich . Thanks for reporting the issue!!

I think Android 4.1.x is a bit old but 5.x is definitely worth to support. I'll be working on it in couple of days. In case you find any solution on your own, remember that Pull Requests are always welcome.

Thank you

**Comment by koljanich** [comment]
As I know, on Android 5.0 is the problem vith save files. For example in file maagers I can't move files - only delete. Maybe this is problem? Maybe need special rights to write to memory?

**Comment by thedoritos** [comment]
Hi, @koljanich. Sorry for the late response. I had the hardest week ever :(

I have some questions.

1) Are you running the sample project or your own? I run the sample and tried to reproduce the bug with an AVD with API 22 and RAM 512 MB but it has not.

2) Could you provide the error logs? It may be printed on LogCat. The whole log is not needed. Only around the exception stack trace is enough.
