### ISSUE TITLE
How do we crop the image ?

### ISSUE THREAD

**Issue by adityaspt** [thedoritos/unimgpicker#40]
The image picker takes only certain resolution. What if i have a landscape type image which i need to crop ?

**Comment by thedoritos** [comment]
Hi, @adityaspt . Thanks for your feedback!

Currently, this library is not planned to add image cropping feature. You have to provide the feature yourself.

**Comment by adityaspt** [comment]
> Hi, @adityaspt . Thanks for your feedback!
> 
> Currently, this library is not planned to add image cropping feature. You have to provide the feature yourself.

Okay do you have any idea on how could i do it. I googled it but did not find anything relevant. If you know any other resource for doing that can you put a link or something for it?

**Comment by thedoritos** [comment]
I'm sorry. I don't have a specific idea. And I wonder this might be off topic for this repository.

Unimgpicker doesn't have a feature to crop image because I think the feature really depends on each application.

I wish you can find a solution. Thank you.
