### ISSUE TITLE
can we make two cube and then ...........

### ISSUE THREAD

**Issue by stickylabdev** [thedoritos/unimgpicker#41]
using diferent show picker button then we choose different image for each diferent cube ?

**Comment by thedoritos** [comment]
Hi, @muafakul. Thanks for your attention to unimgpicker.

You should be able to choose different images each time you open the picker.
But you have to keep the textures instead of keeping the paths.
This is because unimgpicker returns a cached image path that is shared with all the images.

Thank you.

**Comment by stickylabdev** [comment]
![image](https://user-images.githubusercontent.com/13078369/81084406-00996600-8f20-11ea-9140-2836fb58f11c.png)


i still dont understand how to do it ,,what i want is ,,,,,,,something like this ,,,,,,,,,,,


i choose some image for the head

then i choose other image for the body


,,,,,,,,,, i have tried so many times and failed

**Comment by stickylabdev** [comment]
when i click show picker ,, then choose the image ,,then the head should changed 

when i click second show picker ,,,  then choose the image ,,then the body should changed 


it is a sparated spriterenderer

how to do it ?

**Comment by thedoritos** [comment]
You might have to do something like following.
Please note that I just made up the code and I'm not even sure that the code can be compiled.

```csharp
// Initialize
imagePicker.Completed += (string path) =>
{
    if (path.Contains("head_image")) { /* Assign head */ }
    if (path.Contains("body_image")) { /* Assign body */ }
};

// Select Head
imagePicker.Show("Select Head", "head_image", 320);

// Select Body
imagePicker.Show("Select Body", "body_image", 640);
```

The topic seems to be how to implement your application.
I believe this repository is not where to discuss about it.

BTW, I was happy to know what you're developing with unimgpicker.
I hope you can get to your goal!

Thank you :)

**Comment by stickylabdev** [comment]
Ah ok. I appreciate your help. Thanks
