### ISSUE TITLE
Doesn't work on IOS device

### ISSUE THREAD

**Issue by andreyshade** [thedoritos/unimgpicker#45]
I have an issue on mobile device when I pick the image image browser opens but then I get error message in console : "endMessage: object Unimgpicker not found!"

**Comment by thedoritos** [comment]
Hi, @andreyshade. Thx for your feedback.

It seems the `send message` call is failing because a GameObject named `Unimgpicker` does not exists on your scene.
Make sure that your scene contains an object with Unimgpicker.cs attached and it is named as `Unimgpicker`.

**Comment by andreyshade** [comment]
Thanks @thedoritos, it works! I added Unimgpicker to game object with different name before.
