### ISSUE TITLE
リサイズ機能を戻して欲しい＋Windows対応しました

### ISSUE THREAD

**Issue by rarafy** [thedoritos/unimgpicker#46]
自前でunimgpickerを改造し、
1. Windows対応
2. 画像圧縮＋リサイズ
機能を付けました。便利なので、可能であればオリジナルリポジトリにマージしたく思っています。

しかしながら、この拡張はバージョン1.1.2を基に作られたもので、2番のリサイズ機能を利用するためにはバージョン2.0.0で廃止された、イメージリサイズ機能（maxSize）が必須です。
また、個人的にもイメージリサイズ機能は非常に重要で、必須の機能だと考えているため、この機能の廃止をあまり好ましく思っていません。

コード自体は[こちらのリンク](https://github.com/rarafy/unimgpicker-plus)で公開しています。
可能であれば、プルリクエストを送ってマージしたいです。

**Comment by rarafy** [comment]
リサイズ機能を元に戻して欲しい件について補足させて頂きます。
現行バージョン（2.x）では、数十MBの画像が読み込めない不具合があります（私の端末だけかもしれませんが）。
また、仮に読み込めたとしても、帯域幅を食いつぶしてしまうので、そのサイズではサーバにアップロード出来ません。

Xperia XZ2で検証を行いました。

画像のリサイズ機能が廃止されたので、Unity側のTexture2D.Resizeを使うと・・・・
モバイル端末の性能が足りずにアプリが落ちてしまう結果となりました。
30MBくらいの画像をそのまま読み込んだ場合にもアプリが落ちてしまい、結局ネイティブ側で対応するしかなさそうでした。

そこで、引数からmaxSizeを無くすのではなく、**maxSizeが0だったらリサイズ処理を行わないという方向**ではどうでしょうか？
これなら、将来対応するプラットフォームが増えても問題なく、AndroidやiOSでも数十MBという巨大なファイルを問題なく読み込むことが出来るのではないかと思います。

**Comment by thedoritos** [comment]
こんにちは @rarafy さん。フィードバックをありがとうございます。

少し僕の方でも調べてみますね。最新版の Unity と古めの Android 端末で unimgpicker のサンプルを起動した場合に Android ネイティブプラグインの起動に失敗しているかもしれないことがわかったので、そこの調査から始める必要がありそうです。少し時間がかかるかもしれません。

これまでの見解をお伝えしておきます。

### リサイズ機能を落とした経緯

リサイズ機能を 2.x で落とした経緯としては、以下の理由があります。

・モバイル端末によってはリサイズ処理に時間がかかるので、Unity 側の UI が停止してしまう
・リサイズするときに EXIF 情報が失われてしまう（特に orientation の情報が失われてしまう）

参考：https://github.com/thedoritos/unimgpicker/pull/44

解決策として、ネイティブ側から非同期でコールバックする。ネイティブ側で EXIF を書き換える。という方法もありえるとは思いますが、
メンテナンスの負担とライブラリへの依存を減らすという観点により、今のところ採用していません。

### Windows 版の追加について

リサイズ機能を含まない状態での Windows 機能追加であれば、すぐにでも PR を投げてもらう形で大丈夫です。
ただし、それだと @rarafy さんにとってやりやすい方法なのかが気になっています。

リサイズ機能を Unity 側のアプリケーションコードとして分離できるのであれば、それが一番シンプルだと思いますが、Windows ネイティブの API が必要といった理由で Unity 側に分離することが難しい場合、少し対応方法を考えたいです。

全てのプラットフォームに同様のリサイズ機能を用意するのは、メンテナンスの負担になりそうなので、リサイズ機能は Windows のみの提供となると思います。

その場合でも、クロスプラットフォームで簡素かつ堅牢なインターフェースにできると良いなと思っています。
maxSize が 0 だったらリサイズ処理を行わないという方向は、内部実装としては良いと思いますが、アプリケーションから使うときに、

- maxSize = 0 という条件が分かりやすいのか
- 対応している / していないプラットフォームがどれか分かるのか

を少し気にしています。

### For English readers

On this issue, we're discussing about...

- whether we should recover Image Resizing feature that was deprecated on 2.x or not.
    - And how can we keep the API simple and robust
- how can we merge an extension for Windows platform developed by @rarafy.
    - The code is hosted on https://github.com/rarafy/unimgpicker-plus

Currently, the discussion is ongoing in Japanese. However, any ideas from any speakers are appreciated.
I will post a brief decision record at the end of whole discussion.

**Comment by rarafy** [comment]
### リサイズ機能の技術的な検討
リサイズ機能、**実はUnity側のアプリケーションコードとして分離できるのですが、モバイルでやるとアプリが落ちる** という致命的な欠陥を持ちます。
Windowsもスペックが低い機体だと途中でアプリが落ちます。

- リサイズ機能（[［Unity］Texture2Dのサイズを変更する方法｜ひつじTips](https://mu-777.hatenablog.com/entry/2020/02/22/185225)を参考）
```
    static Texture2D ResizeTexture(Texture2D srcTexture, int newWidth, int newHeight) {
        var resizedTexture = new Texture2D(newWidth, newHeight);
        Graphics.ConvertTexture(srcTexture, resizedTexture);
        return resizedTexture;
    }
```
やってることは実質的に```Texture2D.Resize()```と同じです。まさしくリサイズ機能の分離と言えますが、正直ネイティブで実装したほうが圧倒的にパフォーマンスの良い結果が得られます。

- 現在使用している圧縮方法（[私のレポジトリ](https://github.com/rarafy/unimgpicker-plus)）
```
        // テクスチャ取得
        texture = www.texture;
        // スケールのやり直し
        int _CompressRate = TextureCompressionRate.TextureCompressionRatio(texture.width, texture.height);
        TextureScale.Bilinear(texture, texture.width / _CompressRate, texture.height / _CompressRate);
        // 圧縮
        texture.Compress(false);
```
下の方法は、容量を若干減らせますが、実は大して減りません。なので、数十MBの画像をアップロードする場合には使えません。特にFirebaseとの相性が絶望的に悪いです。
<br>
### Windows版の追加
基本的には、Windowsに含まれているSystem.Windows.Forms.dllをUnityの中に組み込んでしまえばそのまま使えるようになっています。
（WindowsネイティブAPIを使ってリサイズ機能を実装すると、追加でImage系のdllが２個必要になります）

PRに向けて準備を進めています。１週間程度時間を頂くと思いますので、少しお待ちください。
<br>
### MaxSize=0
1. 注釈の使用
![image](https://user-images.githubusercontent.com/33755507/131443739-46548bdc-e92d-447a-bd66-41ca40325bb6.png)
summaryを書くとカーソルでメソッドにマウスオーバしたときに注釈を出すことが出来ます。
ReadMeに○○のプラットフォームでは使えません、といった形で直接書いてしまっても良いかもしれません。

あとは、

2. どっちでも良いことにしてしまう
![image](https://user-images.githubusercontent.com/33755507/131444429-a71c101c-80ac-4eba-9f0e-d67b8d6cfae8.png)
ソースを直接見て、気づいた人が下のメソッドを使います。

3. 第三引数 _maxSize_ を省略可能な引数としてしまう
![image](https://user-images.githubusercontent.com/33755507/131444705-16f6808a-ca2d-480f-8e34-f28612040b09.png)
この場合は```show(title, outputFileName)```でもOKということになります。

などの解が現実的だと思います。

**Comment by rarafy** [comment]
As mentioned in #48, close this Issue.
This is due to man-hours and effort.
