### ISSUE TITLE
Getting error when build with android 'gradle' system 

### ISSUE THREAD

**Issue by initfusion** [thedoritos/unimgpicker#8]
this is error 

* What went wrong:
Execution failed for task ':transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't write [/Users/initfusion/Documents/Project/Temp/gradleOut/build/intermediates/transforms/proguard/release/jars/3/1f/main.jar] (Can't read [/Users/initfusion/Documents/Project/Temp/gradleOut/build/intermediates/exploded-aar/gradleOut/Unimgpicker/unspecified/jars/libs/unimgpicker.jar(;;;;;;**/*.class)] (Duplicate zip entry [unimgpicker.jar:com/kakeragames/unimgpicker/BuildConfig.class]))

**Comment by thedoritos** [comment]
Hi @initfusion 

What branch of unimgpicker are you using?
Try `fix/image_rotation` branch if you haven't. I'm trying to support gradle build in it.

Thank you.

**Comment by initfusion** [comment]
Hi @thedoritos 

Thank you for quick replay...
`fix/image_rotation` branch solve my problem thank you very much for help you save my time.

Thank you.
